# Generated by Django 3.2 on 2021-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='how_many_players',
            field=models.TextField(),
        ),
    ]
