# Generated by Django 3.2 on 2021-05-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_type_gametype_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='User',
            new_name='user',
        ),
    ]
