# Generated by Django 3.2 on 2021-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_alter_game_how_many_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
