# Generated by Django 3.2 on 2021-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20210507_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateField(default=''),
        ),
    ]
